name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy on VM
        run: |
          export KUBECONFIG=/root/.kube/config

          cd /DATA/test2/k8s

          docker pull sihyuk11/client_repo:latest

          kubectl rollout restart deployment client-repo -n tcp-client
